site_name: Cool Spy's Site
site_url: 

repo_url: https://github.com/SHenpengYU01/3
repo_name: cool spy
edit_uri: edit/main/docs
theme:
  name: material
  
  palette: 
    scheme: default
    primary: light green
    accent: indigo
  features:
    - instant
    - content.code.annotate
    - content.code.copy
    - content.code.copy_button

nav:
  - Home: home.md
  - Study: 
    - Maths:
      - Linear Algebra: study/math/linear algebra.md
      - Mathematics Analysis: study/math/mathematics analysis.md
      - Discrete Mathematics: study/math/discrete math.md
    - Computer Science: 
      - Datestructure: study/cs/datastructure.md
  - Animation: Animation/animation.md
  - About: about.md


plugins:
  - tags
  - collapsible

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences




extra_javascript:
  - js/custom.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"

